### ISSUE TITLE
Missing build instructions

### ISSUE THREAD

**Issue by ZeroCoolHacker** [shanmugharajk/react-point-of-sale#3]
Hi There!
This is a really nice project. I would love it if you would provide the build instructions

**Comment by shanmugharajk** [comment]
Hi @ZeroCoolHacker 

Actually I heaved stopped development in the master branch which has nodejs/expressjs/reactjs.

To check the current code so far, please follow the following

1. After cloning the repository navigate to `pos-api` and `pos-ui` folders invidually and run `yarn ` in both the folders.

2.  The run `yarn start` in both the folders. For username and password kindly check the `https://github.com/shanmugharajk/react-point-of-sale/blob/master/pos-api/database.sqlite` file please.

I didn't add instructions because I stopped the development in the current master branch.

But I am actively working the backend migration to elixir/phoenix and react with hooks/material ui latest version along with typescript. 

Once I am done with that I will add a demo link along with all clear instructions.

Thanks!

**Comment by ZeroCoolHacker** [comment]
Thanks for the instructions!

**Comment by chileshemartin** [comment]
Hi @shanmugharajk , are you working on this project?
